/* Generated by genhack.py */
#ifdef _FINJ_HOOK_H

#ifdef HAVE_finj_open
#undef finj_open
#undef HAVE_finj_open
#endif /* HAVE_finj_open */

#ifdef HAVE_finj_openat
#undef finj_openat
#undef HAVE_finj_openat
#endif /* HAVE_finj_openat */

{% for func_info in func_infos -%}
#ifdef HAVE_finj_{{ func_info.name }}
#undef {{ func_info.name }}
#undef HAVE_finj_{{ func_info.name }}
#endif /* HAVE_finj_{{ func_info.name }} */

{% endfor %}
#undef _FINJ_HOOK_H
#endif /* _FINJ_HOOK_H */