/* Generated by genhack.py */
#ifdef _FINJ_HOOK_H

#ifdef HAVE_finj_open
#undef finj_open
#undef HAVE_finj_open
#endif /* HAVE_finj_open */

#ifdef HAVE_finj_openat
#undef finj_openat
#undef HAVE_finj_openat
#endif /* HAVE_finj_openat */

#ifdef HAVE_finj_malloc
#undef malloc
#undef HAVE_finj_malloc
#endif /* HAVE_finj_malloc */

#ifdef HAVE_finj_calloc
#undef calloc
#undef HAVE_finj_calloc
#endif /* HAVE_finj_calloc */

#ifdef HAVE_finj_realloc
#undef realloc
#undef HAVE_finj_realloc
#endif /* HAVE_finj_realloc */

#ifdef HAVE_finj_mmap
#undef mmap
#undef HAVE_finj_mmap
#endif /* HAVE_finj_mmap */

#ifdef HAVE_finj_fstat
#undef fstat
#undef HAVE_finj_fstat
#endif /* HAVE_finj_fstat */

#ifdef HAVE_finj_lstat
#undef lstat
#undef HAVE_finj_lstat
#endif /* HAVE_finj_lstat */

#ifdef HAVE_finj_fstatat
#undef fstatat
#undef HAVE_finj_fstatat
#endif /* HAVE_finj_fstatat */

#ifdef HAVE_finj_creat
#undef creat
#undef HAVE_finj_creat
#endif /* HAVE_finj_creat */

#ifdef HAVE_finj_lseek
#undef lseek
#undef HAVE_finj_lseek
#endif /* HAVE_finj_lseek */

#ifdef HAVE_finj_read
#undef read
#undef HAVE_finj_read
#endif /* HAVE_finj_read */

#ifdef HAVE_finj_write
#undef write
#undef HAVE_finj_write
#endif /* HAVE_finj_write */

#ifdef HAVE_finj_close
#undef close
#undef HAVE_finj_close
#endif /* HAVE_finj_close */

#ifdef HAVE_finj_fopen
#undef fopen
#undef HAVE_finj_fopen
#endif /* HAVE_finj_fopen */

#ifdef HAVE_finj_fdopen
#undef fdopen
#undef HAVE_finj_fdopen
#endif /* HAVE_finj_fdopen */

#ifdef HAVE_finj_freopen
#undef freopen
#undef HAVE_finj_freopen
#endif /* HAVE_finj_freopen */

#ifdef HAVE_finj_rename
#undef rename
#undef HAVE_finj_rename
#endif /* HAVE_finj_rename */

#ifdef HAVE_finj_renameat
#undef renameat
#undef HAVE_finj_renameat
#endif /* HAVE_finj_renameat */

#ifdef HAVE_finj_link
#undef link
#undef HAVE_finj_link
#endif /* HAVE_finj_link */

#ifdef HAVE_finj_linkat
#undef linkat
#undef HAVE_finj_linkat
#endif /* HAVE_finj_linkat */

#ifdef HAVE_finj_unlink
#undef unlink
#undef HAVE_finj_unlink
#endif /* HAVE_finj_unlink */

#ifdef HAVE_finj_unlinkat
#undef unlinkat
#undef HAVE_finj_unlinkat
#endif /* HAVE_finj_unlinkat */

#ifdef HAVE_finj_truncate
#undef truncate
#undef HAVE_finj_truncate
#endif /* HAVE_finj_truncate */

#ifdef HAVE_finj_ftruncate
#undef ftruncate
#undef HAVE_finj_ftruncate
#endif /* HAVE_finj_ftruncate */

#ifdef HAVE_finj_remove
#undef remove
#undef HAVE_finj_remove
#endif /* HAVE_finj_remove */

#ifdef HAVE_finj_symlink
#undef symlink
#undef HAVE_finj_symlink
#endif /* HAVE_finj_symlink */

#ifdef HAVE_finj_symlinkat
#undef symlinkat
#undef HAVE_finj_symlinkat
#endif /* HAVE_finj_symlinkat */

#ifdef HAVE_finj_opendir
#undef opendir
#undef HAVE_finj_opendir
#endif /* HAVE_finj_opendir */

#ifdef HAVE_finj_fdopendir
#undef fdopendir
#undef HAVE_finj_fdopendir
#endif /* HAVE_finj_fdopendir */

#ifdef HAVE_finj_mkdir
#undef mkdir
#undef HAVE_finj_mkdir
#endif /* HAVE_finj_mkdir */

#ifdef HAVE_finj_mkdirat
#undef mkdirat
#undef HAVE_finj_mkdirat
#endif /* HAVE_finj_mkdirat */

#ifdef HAVE_finj_rmdir
#undef rmdir
#undef HAVE_finj_rmdir
#endif /* HAVE_finj_rmdir */

#ifdef HAVE_finj_mkdtemp
#undef mkdtemp
#undef HAVE_finj_mkdtemp
#endif /* HAVE_finj_mkdtemp */

#ifdef HAVE_finj_mkstemp
#undef mkstemp
#undef HAVE_finj_mkstemp
#endif /* HAVE_finj_mkstemp */

#ifdef HAVE_finj_mkfifo
#undef mkfifo
#undef HAVE_finj_mkfifo
#endif /* HAVE_finj_mkfifo */

#ifdef HAVE_finj_mkfifoat
#undef mkfifoat
#undef HAVE_finj_mkfifoat
#endif /* HAVE_finj_mkfifoat */

#ifdef HAVE_finj_dup
#undef dup
#undef HAVE_finj_dup
#endif /* HAVE_finj_dup */

#ifdef HAVE_finj_dup2
#undef dup2
#undef HAVE_finj_dup2
#endif /* HAVE_finj_dup2 */

#ifdef HAVE_finj_pread
#undef pread
#undef HAVE_finj_pread
#endif /* HAVE_finj_pread */

#ifdef HAVE_finj_pwrite
#undef pwrite
#undef HAVE_finj_pwrite
#endif /* HAVE_finj_pwrite */

#ifdef HAVE_finj_chdir
#undef chdir
#undef HAVE_finj_chdir
#endif /* HAVE_finj_chdir */

#ifdef HAVE_finj_fchdir
#undef fchdir
#undef HAVE_finj_fchdir
#endif /* HAVE_finj_fchdir */

#ifdef HAVE_finj_chown
#undef chown
#undef HAVE_finj_chown
#endif /* HAVE_finj_chown */

#ifdef HAVE_finj_fchown
#undef fchown
#undef HAVE_finj_fchown
#endif /* HAVE_finj_fchown */

#ifdef HAVE_finj_lchown
#undef lchown
#undef HAVE_finj_lchown
#endif /* HAVE_finj_lchown */

#ifdef HAVE_finj_fchownat
#undef fchownat
#undef HAVE_finj_fchownat
#endif /* HAVE_finj_fchownat */

#ifdef HAVE_finj_chmod
#undef chmod
#undef HAVE_finj_chmod
#endif /* HAVE_finj_chmod */

#ifdef HAVE_finj_fchmod
#undef fchmod
#undef HAVE_finj_fchmod
#endif /* HAVE_finj_fchmod */

#ifdef HAVE_finj_fchmodat
#undef fchmodat
#undef HAVE_finj_fchmodat
#endif /* HAVE_finj_fchmodat */

#ifdef HAVE_finj_getgrnam
#undef getgrnam
#undef HAVE_finj_getgrnam
#endif /* HAVE_finj_getgrnam */

#ifdef HAVE_finj_getgrgid
#undef getgrgid
#undef HAVE_finj_getgrgid
#endif /* HAVE_finj_getgrgid */

#ifdef HAVE_finj_getpwnam
#undef getpwnam
#undef HAVE_finj_getpwnam
#endif /* HAVE_finj_getpwnam */

#ifdef HAVE_finj_getpwuid
#undef getpwuid
#undef HAVE_finj_getpwuid
#endif /* HAVE_finj_getpwuid */

#ifdef HAVE_finj_kill
#undef kill
#undef HAVE_finj_kill
#endif /* HAVE_finj_kill */

#ifdef HAVE_finj_nice
#undef nice
#undef HAVE_finj_nice
#endif /* HAVE_finj_nice */


#undef _FINJ_HOOK_H
#endif /* _FINJ_HOOK_H */