/* Generated by genhack.py */
#ifndef _FINJ_HOOK_H
#define _FINJ_HOOK_H

#include <dirent.h>

#ifndef open
int finj_open(const char *file, const char *caller, int line, const char * pathname, int flags, ...);
#define open(...) finj_open(__FILE__, __func__, __LINE__, ##__VA_ARGS__)
#define HAVE_finj_open
#endif /* open */

#ifndef openat
int finj_openat(const char *file, const char *caller, int line, int dirfd, const char * pathname, int flags, ...);
#define openat(...) finj_openat(__FILE__, __func__, __LINE__, ##__VA_ARGS__)
#define HAVE_finj_openat
#endif /* openat */

{% for func_info in func_infos %}
#ifndef {{ func_info.name }}
{{ func_info.ret_type }} finj_{{ func_info.name }}(const char *file, const char *caller, int line{% if func_info.has_params() %}, {% endif %}{{ func_info.params_str() }});
#define {{ func_info.name }}(...) finj_{{ func_info.name }}(__FILE__, __func__, __LINE__, ##__VA_ARGS__)
#define HAVE_finj_{{ func_info.name }}
#endif /* {{ func_info.name }} */
{% endfor %}

#endif /* _FINJ_HOOK_H */